### ISSUE TITLE
Failure to compile with python-pyqt5.

### ISSUE THREAD

**Issue by hgaiser** [ros-melodic-arch/ros-melodic-qt-gui-cpp#13]
This packages fails to compile on the last version of python-pyqt5. The error you get is:

```shell
[ 89%] Running SIP generator for qt_gui_cpp_sip Python bindings...
Traceback (most recent call last):
  File "/opt/ros/melodic/share/python_qt_binding/cmake/sip_configure.py", line 50, in get_sip_dir_flags
    sip_dir = config.pyqt_sip_dir
  File "/usr/lib/python3.8/site-packages/sipconfig.py", line 192, in __getattr__
    raise AttributeError("\"%s\" is not a valid configuration value or user option" % name)
AttributeError: "pyqt_sip_dir" is not a valid configuration value or user option

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/ros/melodic/share/python_qt_binding/cmake/sip_configure.py", line 86, in <module>
    sip_dir, sip_flags = get_sip_dir_flags(config)
  File "/opt/ros/melodic/share/python_qt_binding/cmake/sip_configure.py", line 66, in get_sip_dir_flags
    raise FileNotFoundError('The sip directory for PyQt5 could not be located. Please ensure' +
FileNotFoundError: The sip directory for PyQt5 could not be located. Please ensure that PyQt5 is installed
make[2]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/build.make:90: sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [CMakeFiles/Makefile2:349: src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
```

`pyqt_sip_dir` points to `/usr/share/sip/Qt5`. This error seems to come from the [change in python-pyqt5](https://git.archlinux.org/svntogit/packages.git/commit/?h=packages/pyqt5&id=bd544723e6262bc978d4a7680eedeef90186dc41). They removed the `pyqt5-common` package which included sip files in `/usr/share/sip/Qt5`, which `ros-melodic-qt-gui-cpp` relies on.

Is this an issue with upstream `python-pyqt5`? Or maybe in `qt_gui_cpp`? Or is this something to be resolved in the PKGBUILD?

**Comment by jwhendy** [comment]
![image](https://user-images.githubusercontent.com/379357/72259163-6068ab80-35d5-11ea-9a6c-5a35188285fb.png)

Dup: https://github.com/ros-melodic-arch/ros-melodic-rviz/issues/9
